const mongoose=require("mongoose");
const Schema=mongoose.Schema;

const productschema = Schema(
    {
        Crop_Name:
        {
            type:String,
            required:true
        },
        Description:
        {
            type:String,
            required:true
        },
        Contact:
        {
            type:Number,
            required:true
        },
        /*Country:
        {
            type:String,
            required:true
        },
        City:
        {
            type:String,
            required:true
        },
        State:
        {
            type:String,
            required:true
        },*/
        Location:
        {
            type:String,
            required:true
        },
        Quantity:
        {
            type:Number,
            required:true
        },
        Unit:
        {
            type:String,
            required:true
        },
        Price_per_unit:
        {
            type:Number,
            required:true
        },
        ImageURL:
        {
           type:String,
           required:true
        },
        Feedbacks:
        {
            type:[String]
        },
        Owner:
        {
            type:String,
            required:true
        }
    }
)

module.exports=mongoose.model('product',productschema);